<!DOCTYPE HTML>
<html>
<header>
<title> Smart Soft Experts:Software Development Company</title>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <meta name="the scorpions" content="">
    <meta name="keywords" content="Website designers,Smart soft expert,software applications,IT consultant,web hosting,cheap website developers,website builders in Kenya,Unganda,Tanzania,Mombasa,Nairobi">
    <meta name="description" content="Smart Soft Experts is a Custom Software development Company.We provide professional web design and Custom software development services to small and corporate business.<">
    <link rel="icon" href="../../favicon.ico">
	  <!-- Bootstrap core CSS -->
	 
    <link href="css/bootstrap.min.css" rel="stylesheet">
	<link href="stylesoft.css" rel="stylesheet" type="text/css" media="screen" />
</header>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="jumbotron">
<div class="container">
    <div class="row">
	    <div class="  panel col-md-12">
		  <div class="row"> 
		    <div class=" col-md-12 btn-default">
			  <div class="col-md-4 col-md-offset-">
			  <div class=" col-md-offset- text-pull-">
			 <em> Thanks for your confidence in our service</em>
			   </div>
			  </div>
			  <div class="col-md-4 col-md-offset-0">
			  Find us on:
			       <a href="http://www.facebook.com/francis.kihiko"><img src="img/facebook (1).png" height="25px" width="25px"/></a.
			       <a href="http://www.twitter.com/FKihiko"><img src="img/twitter.png" height="25px" width="25px"/></a>
			      <a> <img src="img/rss.png" height="20px" width="20px"/></a>
			      <a href="http://ke.linkedin.com/pub/smart-soft-experts/a8/ba4/442"> <img src="img/linkedin.png" height="20px" width="20px"/></a>
			      <a href="http://ke.linkedin.com/pub/smart-soft-experts/a8/ba4/442"> <img src="img/pinterest.png" height="20px" width="20px"/></a>
				   <img src="img/download (4).jpg" height="25px" width="25px"/>  &nbsp; 0707071957
			  </div>
			  
			  <div class="col-md-3 col-md-offset-1">
			   <a href="order.php"><button  class="button  btn-danger"><span class="badge ">Order Now</span></button></a>
			  </div>
			</div>
		  </div>	
	  <div class="row">
	       <div class=" col-md-12 btn-success">
		     <div class="col-md-5 media">
<a class="pull-left" href="#">
<img class="media-object img-circle" src="img/sse.png" height="150px" width="150px"
alt="Media Object">
</a>
<div class="media-body">
</br>
<h3 class="media-heading"><b>Smart Soft Experts</b></h3>
<em>Providing business solutions through software applications</em>
</div>
</div>
			<div class="col-md-4">
			<b>
			</br>
			Best web designers & Software Developers
			   </b></br>
			   <em>Thanks for choosing and making us to be who </br>we are today.</em>
			</div>
			<div class="col-md-3 col-md-offset-"></br>
			    <span class="glyphicon glyphicon-phone-alt btn-lg-4 "> </span> &nbsp; 0707071957</br></br>
			    <span class="glyphicon glyphicon-phone-alt btn-lg-4"> </span> &nbsp; 0707071957</br></br>
			    
			    <span class="glyphicon glyphicon-envelope"> </span>&nbsp; info@smartsoftexperts.com</br>
			</div>
			 
		  </div>
	 </div>
	 <div class="row">
	    <div class="col-md-12 penel-danger" style="background-color:black;color:white">
<ul class="nav nav-tabs " style="background-color;font:20px arial;">
<li class=""><a href="index.php" style="color:white;"><span class="glyphicon glyphicon-home"></span>Home</a></li>
<li><a href="aboutus.php" style="color:white">About us</a></li>
<li><a href="order.php" style="color:white">Website Design</a></li>
<li><a href="seo.php" style="color:white">SEO</a></li>
<li><a href="software.php" style="color:white">Software Development</a></li>
<li><a href="contactus.php" style="color:white">Contact Us</a></li>
<li><a href="blog.php"  style="color:white">Blog</a></li>
</ul>
		
	
	</div>
	 </div>
  <div class="row">
        <div class="col-md-10">
		 <?php
		include("slide.php");
		 
		 ?>
		
		</div>
		<div class="col-md-2">
		 <form role="form" method="POST" action="index.php">
		 </br> 
		<a  data-target="#myModal" data-toggle="modal" data-target="#myModal"  class="list-group btn btn-danger divider " ><span class="glyphicon glyphicon-envelope">
		</span> Send Us an SMS </br><img src="img/images (2).jpg" height="120px" width="150px" /></a>
		   
		   <!--modal-->
                  <div class="modal " id="myModal" tabindex="-4" role="dialog" aria-labelLedby="myModalLabel" aria-hidden="false">
				     <div class="modal-dialog">
					     <div class="modal-content">
						    <div class="modal-header">
							    <button type="button" class="close" data-dismiss="modal" aria-hidden="">&times </button>
								<h2 class="modal-title" id="myModalLabel">Send us a short message </h2>
								
							</div>
							<div class="modal-body">
							  <b><marquee>We are ready to walk with you through this jouney</marquee></b>
							<hr/>
							 
							     <div class="form-group">
								      <div>
									    <input class="form-control" type="tel" required name="contact" placeholder="Please enter your email or mobile no here" maxlength="13"/>
									  </div></br></br>
									  <div>
									    <textarea class="form-control" required type="text" name="message" rows="4" maxlength="70" placeholder="Please enter your message here"></textarea>
									  </div>
									  
								 </div>
							  
							  </br>
							  </br>
							  
							</div>
							<div class="modal-footer">
							  <button type="submit" class="btn btn-success" name="send" >Send</button>
							   <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
							  
							  
							</div>
						 </div>
					 </div>
				  </div> 
				</form>
				   <?php
				                 if(isset($_POST['send']) && isset($_POST['contact'])&& isset($_POST['message']))
					 
					                    { 
										    $contact=htmlentities($_POST['contact']);
										    $message=htmlentities($_POST['message']);
											  $to="kfranciskihiko2013@gmail.com";
											  $subject=$contact;
											  $body=$message;
											  $header="From:".$contact;
											  if(mail($to,$subject,$body,$header))
											   {  ?>
											     	      <script>
                          alert('SENT SUCCESSFULY! We will be in touch soon');
                         window.location.href='index.php?';
                          </script> 
											   <?php }
											   else{?> 
											     <script>
                          alert('Sorry! message was not sent, Please try again');
                         window.location.href='index.php?';
                          </script> 
											   <?php }
                                              
											  
					                    }
				               ?>
							  
							   
							   

	 
				 </div> 
					  
              
		</div>
   </div>
  <div  class="row">
       <div class="col-md-12" style="background-color:black;color:white">
	      <marquee> Welcome to our website</marquee>
		  
	   </div>
  </div> 
 <div class="row">
     <div class="col-md-12">
	     <div class="col-md-4">
	       <div class="panel panel-success ">
		        <div class="panel-heading">
				   <b> SEO</b>
				</div>
				<div class="panel-body">
				    How many times have you typed into any search engine such as Google 
					and yahoo the term that best describe your business and been been instantly deflated when you see the words: 
					‘About 5,000,000,000 results’!.We understand how daunting
					it can be, but you will be surprised at how much rubbish is out there.</br></br>
					No matter how much you spent on your website,Search Engine Optimization is an integral factor of consideration for higher ranking of your website in Google index and other search engine...
					</br>
					 <div class="pull-right">
					  <a href="seo.php"><button class="button btn-success"> <span class=" badge btn-danger">Read More >></span></button></a>
					 </div>
				</div>
				
		   </div>
		  </div>
		  <div class="col-md-4">
	       <div class="panel panel-success ">
		        <div class="panel-heading">
				   <b> Website Design Services</b>
				</div>
				<div class="panel-body">
				   We provide professinal web design services to individuals,small business and Corporates <em>Available web packages</em>
				   <ul class="list-group">
				     
				     <li class="list-group-item">Basic Package&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="col-md- pull-right text-danger">Ksh.13,000</span> </li>
				     <li class="list-group-item">Standard Package &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="col-md- pull-right text-danger">Ksh.30,000</span></li>
				     <li class="list-group-item">Professional Package &nbsp;&nbsp;&nbsp;&nbsp; <span class="col-md- pull-right text-danger">Ksh.50,000</span></li>
				     <li class="list-group-item">Corporates Package &nbsp; <span class="col-md- pull-right text-danger">Ksh.100,000</span></li>
				   </ul>
					
					 <div class="pull-left">
					  <a href="order.php"><button class="button btn-danger"> <span class=" badge btn-danger">Order Now </span></button></a>
					 </div>
					 <div class="pull-right">
					 <a href="order.php"><button class="button btn-success"> <span class=" badge btn-danger">Read More >> </span></button></a>
					 </div>
				</div>
		   </div>
		  </div> 
		  <div class="col-md-4">
	       <div class="panel panel-success ">
		        <div class="panel-heading">
				   <b>Custom Software Development</b>
				</div>
				<div class="panel-body">
				    Being a software development as well as IT consulting company,Smart Soft Experts offer high quality software development services as per client requirement
					and conveniences.</br></br>The use of software for business application management is not a new concept in this world of modernization with the advent
					of technology,software industry is blooming...</br>
					
					<hr/>
					</br></br>
					 <div class="pull-right">
					   <a href="software.php"><button class="button btn-success"> <span class=" badge btn-danger">Read More > ></span></button></a>
					 </div>
				</div>
		   </div>
		  </div>
	 </div>
 </div>
 <div class="row">
          <div class="col-md-12">		  
		         <div class="col-md-8">
				    <div class="panel panel-success ">
		              <div class="panel-heading text-center">
				         <b> Why we are unique</b>
				       </div>
				    <div class="panel-body">
					   <div class="col-md-6">
				         <div class="media">
						     <a class="pull-left" href="#">
                                <img class="media-object img-thumbnail" src="img/images_13.jpeg" height="300px" width="100px"
                                   alt="Media Object" >
                             </a>
                            <div class="media-body">
                             <h4 class="media-heading">30-Days Money Back</h4>
                                We refund 100% maney to our clients who are not satisfied by our service without any question
                               
                            </div>
						 </div>
						</div> 
						<div class="col-md-6">
				         <div class="media">
						     <a class="pull-left" href="#">
                                <img class="media-object img-thumbnail" src="img/icon-passion.png"
                                   alt="Media Object">
                             </a>
                            <div class="media-body">
                             <h4 class="media-heading">Passion is what drive Us</h4>
                                 Providing business solutions through custom softwares and innovative thinking 
								 is our passion</br></br>
                               
                            </div>
						 </div>
						</div> 
						<div class="col-md-6">
				         <div class="media">
						  <hr/>
						     <a class="pull-left" href="#">
                                <img class="media-object" src="img/icon4.png"
                                   alt="Media Object">
                             </a>
                            <div class="media-body">
                             <h4 class="media-heading">Reliability</h4>
                                 We understand the value of time and thus maintain structured working process for gaining on-time results.
                               
                            </div>
						 </div>
						</div> 
						<div class="col-md-6">
				         <div class="media">
						 <hr/>
						     <a class="pull-left" href="#">
                                <img class="media-object" src="img/featuresbar-icon2.png"
                                   alt="Media Object">
                             </a>
                            <div class="media-body">
                             <h4 class="media-heading">Cost effectiviness</h4>
                                Cost effectiviness is the prime fascia of our company! we believe in providing value for money services with a realistic budget.
                               
                            </div>
						 </div>
						</div> 
					<div class="row">
					    <div class="col-md-12">
						<hr/>
						<div class="text-center btn-danger"><b>Some of our happy Clients</b></div></br>
						<img src="img/smartfarm.png" class="img-" width="200px" height="100px"/>&nbsp;&nbsp;&nbsp;
						<img src="img/ishangel.jpg" class="img-thumbnail" width="200px" height="100px"/>
						<img src="img/sse.png" class="img-" width="200px" height="100px"/>
						</div>
					</div>	
						
				   </div>
		        </div>
				  
				  </div>
				  <div class="rightbar col-md-4">
				         <div class="panel panel-success">
						         <div class="panel-heading">
								     Why Choose Us:
								 </div>
								 <div class="panel-body">
								  <ul class="list-group">
                                      <li class="list-group-item"><span class="glyphicon glyphicon-ok ok-info"></span>&nbsp;Quality is the hallmark of our service</li>
                                      <li class="list-group-item"><span class="glyphicon glyphicon-ok ok-info"></span>&nbsp;We have a dedicated and innovative team having experience and expertise</li>
                                      <li class="list-group-item"><span class="glyphicon glyphicon-ok ok-info"></span>&nbsp;We are passionate about what we do</li>
                                      <li class="list-group-item"><span class="glyphicon glyphicon-ok ok-info"></span>&nbsp;Our support is Unmatched</li>
								 </ul>
								 </div>
						 </div>
						 <div class="panel panel-default">
						      <div class="body">
							  <div class="col-md-off-1">
							    <table width="%" cellspacing=""> 

<tr><td><div class="fb-like-box" data-href="https://www.facebook.com/softexperts"
 data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true" style="width:30%"></div></td></tr>

</table></div>
							  </div>
						 </div>
				  
				  </div>
		  </div>   
 </div>
 <div class="row">
           <div class="col-md-12 btn-" style="background-color:black;">
		   </br>
		   </br>
		  
		         <div class="col-md-3" style="background-color:black; color:white">
				     <a href="#" class=" " style="background-color:black; color:white" >
                      <b> <h3>Web  Services<h3></b>
					  
                     </a>
                      <a href="order.php" class="" style="background-color:black; color:white" ><h5>Website Design</h5></a>
                      <a href="seo.php" class="" style="background-color:black; color:white"><h5>SEO</h5></a>
                      <a href="order.php" class="" style="background-color:black; color:white"><h5>Website maintenance</h5></a>
                      <a href="order.php" class="" style="background-color:black; color:white"><h5>Website re-design</h5> </a>
				 </div> 
				 <div class="col-md-3" style="background-color:black; color:white">
				     <a href="#" class=" " style="background-color:black; color:white" >
                      <b> <h3>Software Development<h3></b>
					  
                     </a>
                      <a href="software.php" class="" style="background-color:black; color:white" ><h5>Mobile Apps</h5></a>
                      <a href="software.php" class="" style="background-color:black; color:white"><h5>Petrol station management system</h5></a>
                      <a href="software.php" class="" style="background-color:black; color:white"><h5>Library System</h5></a>
                      <a href="software.php" class="" style="background-color:black; color:white"><h5>Graphic design <span class="badge">Others</span></h5> </a>
				 </div>
				 <div class="col-md-3" style="background-color:black; color:white">
				     <a href="#" class=" " style="background-color:black; color:white" >
                      <b> <h3> Company<h3></b>
					  
                     </a>
                      <a href="aboutus.php" class="" style="background-color:black; color:white" ><h5>About Us</h5></a>
                      <a href="#" class="" style="background-color:black; color:white"><h5>Blog</h5></a>
                      <a href="#" class="" style="background-color:black; color:white"><h5><b>Can now pay through</b></h5></a>
                      <a href="#" class="" style="background-color:black; color:white"><h5><img class="media-object" src="img/download (1).jpg" height="70px" width="110px"/>
					  <img class="media-object" src="img/paypalicon.png" height="80px" width="100px"/></h5> </a>
				 </div>
				 <div class="col-md-3" style="background-color:black; color:white">
				     <a href="#" class=" " style="background-color:black; color:white" >
                      <b> <h3>  Contact Us<h3></b>
					  
                     </a>
                      <a href="" class="" style="background-color:black; color:white" ><h5><span class="glyphicon glyphicon-phone-alt btn-lg-4 "> </span> &nbsp; 0707071957</h5></a>
                      <a href="" class="" style="background-color:black; color:white"><h5><span class="glyphicon glyphicon-phone-alt btn-lg-4 "> </span> &nbsp; 0707071957</h5></a>
                      <a href="" class="" style="background-color:black; color:white"><h5><span class="glyphicon glyphicon-envelope btn-lg-4 "> </span> &nbsp; info@smartsoftexperts.com</h5></a>
                      <a href="" class="" style="background-color:black; color:white"><img src="img/facebook-icon.png" width="200px" height="30px"/> </a>
                      <a href="" class="" style="background-color:black; color:white"><img src="img/twitter-icon.png" width="200px" height="30px"/> </a>
					 
				 </div>
				
				 
				
			<div class="col-md-12 col-md-offset-" style="color:white;background-color:green">
			          <div class="col-md-offset-3">
		             Copyright © Smart Soft Experts 2015 all right reserved professionals in software development.
					 <a href="condition.php" style="color:red" class="pullright"> Terms of Services</a>
					 </div>
		  </div>
		   </div>
 </div>
 <div class="row">
         
 </div>
 
			
		
		</div>
	</div>
</div>
</div>






<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
	
    <script src="js/bootstrap.js"></script>
    <script src="js/popover.js"></script>
    <script src="../../assets/js/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>